### ISSUE TITLE
Why maintain a fork?

### ISSUE THREAD

**Issue by lucc** [powerman/vim-plugin-AnsiEsc#9]
I just send a bug report to Chip upstream. The bug seems to be solved differnently in your version than what he did to solve it in v13l as I can see a different bug with your version.

So the question is: Did you try to send your changes upstream? Why not? Or why were they rejected? What is the reason for maintaining a fork? (I did not find a comment about this in the Readme)

Also, you link to the vim.org version of the script which is not uploaded any longer. And the original part of the readme is also outdated.

(If you are interested in the bug I mentioned, you can reproduce it with neovim when you view the output of this script: https://github.com/lucc/shell/blob/master/color.sh

**Comment by powerman** [comment]
This fork was created many years ago and I don't remember exact reason (chances are I wanted to merge all fixes found in all github forks into one fork). Usually I do everything I can to avoid creating forks which I'll have to support myself then and always prefer to contact author/make PR instead of forking - so I suppose I've at least tried to contact author at that time. Another reason might be the absence of public repo, because that's really convenient.

I didn't use this plugin myself in last years, but do my best supporting it when other people report issues/PR.

I believe at this moment there are too many incompatible and massive changes in this fork which makes it very unlikely to push them to original version. But if anyone manages to merge at least most of fixes to author's version then I'll be more than happy to close this fork.

There are usually no sense in uploading to vim.org after each minor commit, so I prefer to wait until there will be some amount of changes in the repo before uploading to vim.org new version. Current version at vim.org is just one commit behind the repo, but that commit is a year-old, so probably it makes sense to upload to vim.org now.

If you see anything wrong/outdated with README - just make a PR. 😄

I don't use neovim, but I'll accept a PR which fix neovim issue if it doesn't break anything in vim.
